SKILL_REGISTRY = {
    "TargetLocateMeasureSkill": {
        "executor_model": "TargetLocateMeasureSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/TargetLocateMeasureSkill.md",
        "required_inputs": ["image", "target", "mode"],
        "optional_inputs": [
            "reference_target",
            "gsd_m_per_pixel",
            "visualize",
            "top1",
            "detector",
            "max_draw",
        ],
        "defaults": {
            "visualize": True,
            "top1": False,
            "detector": "auto",
            "max_draw": 10,
        },
        "timeout_sec": 240,
    },
    "SARTargetLocateMeasureSkill": {
        "executor_model": "SARTargetLocateMeasureSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/SARTargetLocateMeasureSkill.md",
        "required_inputs": ["image", "target", "mode"],
        "optional_inputs": [
            "reference_target",
            "gsd_m_per_pixel",
            "visualize",
            "top1",
            "detector",
            "max_draw",
            "preprocess_mode",
            "preprocessed_output_path",
        ],
        "defaults": {
            "visualize": True,
            "top1": False,
            "detector": "auto",
            "max_draw": 10,
            "preprocess_mode": "sar_preprocess",
        },
        "timeout_sec": 300,
    },
    "TargetAttributeSkill": {
        "executor_model": "TargetAttributeSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/TargetAttributeSkill.md",
        "required_inputs": ["image", "task_type"],
        "optional_inputs": [
            "target",
            "attribute",
            "attribute_value",
            "compare_mode",
            "selector_a",
            "selector_b",
            "bbox",
            "top1",
            "visualize",
            "max_draw",
            "use_segmentation",
        ],
        "defaults": {
            "visualize": True,
            "top1": False,
            "max_draw": 10,
            "use_segmentation": False,
        },
        "timeout_sec": 180,
    },
    "ConditionalCountSkill": {
        "executor_model": "ConditionalCountSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/ConditionalCountSkill.md",
        "required_inputs": ["image", "target", "condition"],
        "optional_inputs": [
            "bbox",
            "visualize",
            "max_draw",
            "verify_examples",
            "max_verify",
        ],
        "defaults": {
            "visualize": True,
            "max_draw": 10,
            "verify_examples": False,
            "max_verify": 3,
        },
        "timeout_sec": 180,
    },
    "MultConfirmSkill": {
        "executor_model": "MultConfirmSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/MultConfirmSkill.md",
        "required_inputs": ["rgb_image", "sar_image", "target"],
        "optional_inputs": [
            "task_type",
            "preprocess_mode",
            "sar_preprocessed_output_path",
            "iou_threshold",
            "top1",
            "detector",
            "visualize",
            "max_draw",
        ],
        "defaults": {
            "task_type": "confirm",
            "preprocess_mode": "sar_preprocess",
            "iou_threshold": 0.2,
            "top1": False,
            "detector": "auto",
            "visualize": True,
            "max_draw": 10,
        },
        "timeout_sec": 300,
    },
    "ChangeSummarySkill": {
        "executor_model": "ChangeSummarySkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/ChangeSummarySkill.md",
        "required_inputs": ["pre_image", "post_image"],
        "optional_inputs": ["task_type", "query", "target"],
        "defaults": {
            "task_type": "generic",
        },
        "timeout_sec": 300,
    },
    "GeoTIFFPoiExploreSkill": {
        "executor_model": "GeoTIFFPoiExploreSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/GeoTIFFPoiExploreSkill.md",
        "required_inputs": ["geotiff", "poi_specs"],
        "optional_inputs": [
            "task_type",
            "buffer_m",
            "show_names",
            "describe_rendered",
        ],
        "defaults": {
            "task_type": "visualize",
            "show_names": True,
        },
        "timeout_sec": 300,
    },
    "GeoTIFFPoiDistanceSkill": {
        "executor_model": "GeoTIFFPoiDistanceSkill",
        "md_path": "tool_server/tool_workers/skills/skill_md/GeoTIFFPoiDistanceSkill.md",
        "required_inputs": ["geotiff", "poi_specs"],
        "optional_inputs": [
            "src_layer",
            "tar_layer",
            "buffer_m",
            "top",
            "show_names",
            "render_distance_layer",
            "layers_to_render",
        ],
        "defaults": {
            "top": 1,
            "show_names": True,
            "render_distance_layer": True,
        },
        "timeout_sec": 300,
    },
}